version: '3'
services:
  eureka:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "8761:8761"
    volumes:
      - ~/eureka.jar:/eureka.jar
    command: ["java", "-jar", "eureka.jar"]

  api-gateway:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "9090:9090"
    volumes:
      - ~/api-gateway.jar:/api-gateway.jar
    command: ["java", "-jar", "api-gateway.jar"]

  auth-server:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "8083:8083"
    volumes:
      - ~/auth-server.jar:/auth-server.jar
    command: ["java", "-jar", "auth-server.jar"]

  superadmin:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "8081:8081"
    volumes:
      - ~/superadmin.jar:/superadmin.jar
    command: ["java", "-jar", "superadmin.jar"]

  notification:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "8084:8084"
    volumes:
      - ~/notification.jar:/notification.jar
    command: [ "java", "-jar", "notification.jar" ]

  community:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "8082:8082"
    volumes:
      - ~/community.jar:/community.jar
    command: [ "java", "-jar", "community.jar" ]

  suggestion:
    image: kabiraneja/ubuntu-java-maven
    ports:
      - "8092:8092"
    volumes:
      - ~/suggestion.jar:/suggestion.jar
    command: [ "java", "-jar", "suggestion.jar" ]