server :
  port : 9090

spring :
  application :
    name : API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://192.168.1.9:8083
          predicates:
            - Path=/auth/**
        - id: super-admin
          uri: http://192.168.1.9:8081
          predicates:
            - Path=/user/**
        - id: eureka
          uri: http://192.168.1.9:8761
          predicates:
            - Path=/**

eureka :
  instance :
    prefer-ip-address : true
  client :
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka